### ISSUE TITLE
Sell this doesnt gives the cost of items back 

### ISSUE THREAD

**Issue by prakarsh17** [AyushSehrawat/eco-bot#26]
Sell this doesnt gives the cost of items back

**Comment by prakarsh17** [comment]
@AyushSehrawat PLS HELP , I tried but I failed

**Comment by AyushSehrawat** [comment]
Hm, ig you have to run this function
`async def sell_this(user,item_name,amount,price = None):`
Before sending message, run this `await sell_this(.........)`

**Comment by prakarsh17** [comment]
Oh yeah , i think there was some issue before that it didnt wokr
