### ISSUE TITLE
Python can't download the requirements

### ISSUE THREAD

**Issue by esloveno4u** [AyushSehrawat/eco-bot#32]
![error](https://github.com/AyushSehrawat/eco-bot/assets/162448900/bbb5d56b-f129-4c40-b03d-5ab58406ffb3)

**Comment by AyushSehrawat** [comment]
This project has been unmaintained for quite a few years, probably dependency issue

**Comment by infinotiver** [comment]
Hello, You are still alive @AyushSehrawat ??? !!! Can't believe...

@esloveno4u  you can try updating the versions of requirements, also there is some substantial differences in the newer versions

**Comment by AyushSehrawat** [comment]
> Hello, You are still alive @AyushSehrawat ??? !!! Can't believe...
> 
> @esloveno4u you can try updating the versions of requirements, also there is some substantial differences in the newer versions

Yeah, i just don't do discord bot development anymore.

If you would like to update this repo you can let me know :)

**Comment by infinotiver** [comment]
> If you would like to update this repo you can let me know :)

Surely, if I get some time.. i will be opening a pr soon.

> Yeah, i just don't do discord bot development anymore.

What are you doing right now? Freelancing? 
Why did you leave discord ?

[ Sorry if it is going too off topic/ general, can you contact me on discord or somewhere? ]

**Comment by AyushSehrawat** [comment]
> > If you would like to update this repo you can let me know :)
> 
> Surely, if I get some time.. i will be opening a pr soon.
> 
> > Yeah, i just don't do discord bot development anymore.
> 
> What are you doing right now? Freelancing? Why did you leave discord ?
> 
> [ Sorry if it is going too off topic/ general, can you contact me on discord or somewhere? ]

You can leave you discord username here and i can contact you.

**Comment by infinotiver** [comment]
@infinotiver

I use the same username everywhere... :)

**Comment by infinotiver** [comment]
@esloveno4u  as for your error, ( as per my preliminary analysis ),
the problem is with `psutil` and not the other modules ( this happens usually on Windows devices, specifically )

Try
1. Updating your python version
2. 
```
sudo apt-get install python3.6-dev
````

**Comment by AyushSehrawat** [comment]
Instead of this, checkout https://github.com/giampaolo/psutil/blob/master/INSTALL.rst

That dependency will only work with python 3.6 since it depends on it

Rest, send the error if not solved

**Comment by AyushSehrawat** [comment]
@esloveno4u Try the latest patch submitted by @infinotiver
